theme: jekyll-theme-cayman
title: RML vs Traffic Collisions
description: How recreational marijuana legalization(RML) affects traffic-related scenes in California using Difference in Differences model
