
remote_theme: samanyougarg/hanuman
title: RML vs Traffic Collisions
description: How recreational marijuana legalization(RML) affects traffic-related scenes in California using Difference in Differences model
plugins:
  - jekyll-remote-theme
cover: assets/images/radhakrishna.jpg