FROM r-base

RUN apt-get update

RUN apt-get install -y apt-utils

RUN apt-get install -y libcurl4-openssl-dev

RUN apt-get install -y libssl-dev

RUN apt-get install -y libfontconfig

RUN apt-get install -y libssh2-1-dev

RUN apt-get install -y libudunits2-dev

RUN apt-get install -y libxml2-dev

RUN apt-get install -y libgit2-dev

RUN apt-get install -y libfontconfig1-dev

RUN R -e "install.packages('BiocManager',dependencies=TRUE,repos='http://cran.rstudio.com/')"

RUN R -e "BiocManager::install('limma')"

RUN R -e "BiocManager::install('edgeR')"

RUN R -e "BiocManager::install('Glimma')"

RUN R -e "install.packages('ggplot2',dependencies=TRUE,repos='http://cran.rstudio.com/')"

RUN R -e "install.packages('ggrepel',dependencies=TRUE,repos='http://cran.rstudio.com/')"

RUN R -e "install.packages('gplots',dependencies=TRUE,repos='http://cran.rstudio.com/')"

RUN R -e "install.packages('amap',dependencies=TRUE,repos='http://cran.rstudio.com/')"

RUN R -e "install.packages('reshape2',dependencies=TRUE,repos='http://cran.rstudio.com/')"

RUN R -e "install.packages('rjson',dependencies=TRUE,repos='http://cran.rstudio.com/')"
